server:
    port: 8080
    shutdown: graceful
    servlet:
      session:
        timeout: 10

spring :
    application:
        name: GG-contest-b
    config:
        activate:
          on-profile: default
    # DB 연결
    datasource:
      url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
    # 콘솔 확인 을 위한 always
    output:
      ansi:
        enabled: always
